name: Firebase Deployment
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0
      - name: Install Dependencies
        run: npm install
      - name: Build
        env:
          CI: true
        run: npm run build
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 18.x
      - name: Debug npm scripts
        run: npm run
      - name: Display package.json
        run: cat package.json
      - name: List Directory Contents
        run: ls -l
      
          
        
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4.0.0
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}


